# Generated by Django 5.2.17 on 2026-08-27 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIContentSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(default='product', max_length=40)),
                ('target_id', models.BigIntegerField(blank=True, null=True)),
                ('suggestion_type', models.CharField(choices=[('description', 'Description'), ('tags', 'Tags'), ('moderation', 'Moderation')], max_length=16)),
                ('input_payload', models.JSONField(default=dict)),
                ('structured_output', models.JSONField(default=dict)),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=3)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_suggestions_requested', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_suggestions_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('confidence__gte', 0), ('confidence__lte', 1)), name='ai_confidence_range')],
            },
        ),
    ]
